# Generated by Django 5.1.6 on 2025-03-10 11:55

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_organization_is_approved'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='moderators',
        ),
        migrations.AddField(
            model_name='organization',
            name='moderators',
            field=models.ManyToManyField(blank=True, related_name='moderating_organization', to=settings.AUTH_USER_MODEL),
        ),
    ]
