# Generated by Django 5.1.6 on 2025-03-03 22:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='hackathons',
            field=models.ManyToManyField(related_name='teams', to='hackathon.hackathon'),
        ),
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to=settings.AUTH_USER_MODEL),
        ),
    ]
