# Generated by Django 5.1.6 on 2025-03-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_auth_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='moderators',
        ),
        migrations.RemoveField(
            model_name='organization',
            name='organizer',
        ),
        migrations.RemoveField(
            model_name='team',
            name='hackathons',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
