# Generated by Django 5.1.6 on 2025-03-10 10:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_remove_organization_moderators_and_more'),
        ('hackathon', '0003_alter_prize_recipient_alter_project_team_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Organization',
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
