# Generated by Django 5.1.6 on 2025-03-10 14:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0003_alter_prize_recipient_alter_project_team_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='status',
        ),
    ]
