# Generated by Django 5.1.6 on 2025-03-10 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_remove_hackathon_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hackathon',
            name='end_date',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='start_date',
            field=models.DateField(),
        ),
    ]
