# Generated by Django 5.1.6 on 2025-03-11 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0005_alter_hackathon_end_date_alter_hackathon_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='hackathon',
            name='details',
            field=models.TextField(default='online'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='hackathon',
            name='venue',
            field=models.CharField(default='online', max_length=100),
            preserve_default=False,
        ),
    ]
