# Generated by Django 5.1.6 on 2025-04-14 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0006_hackathon_details_hackathon_venue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='team',
        ),
    ]
