# Generated by Django 5.1.6 on 2025-04-14 13:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0007_remove_project_team'),
        ('organization', '0003_remove_organization_moderators_and_more'),
        ('project', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='project',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='submission', to='project.project'),
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='judges',
        ),
        migrations.RemoveField(
            model_name='theme',
            name='hackathons',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='details',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='grand_prize',
            field=models.IntegerField(default=0, verbose_name='grand prize'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='max_team_size',
            field=models.IntegerField(default=5, verbose_name='maximum team size'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='min_team_size',
            field=models.IntegerField(default=1, verbose_name='minimum team size'),
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='organization',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hackathons', to='organization.organization'),
        ),
        migrations.AlterField(
            model_name='review',
            name='judge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='review',
            name='review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='theme',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Project',
        ),
    ]
